# Base image
FROM python:3.10-slim

# Set working directory
WORKDIR /usr/src/app

# Install dependencies
COPY local-do-files/Pipfile local-do-files/Pipfile.lock ./
RUN pip install pipenv && pipenv install --system --deploy

# Copy the application files
COPY local-do-files/ .

# Expose the port the app runs on
EXPOSE 8050

# Command to run the app
CMD ["python", "app.py"]
