version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_APP=app.web
      - FLASK_ENV=development
      - SECRET_KEY=123
      - SQLALCHEMY_DATABASE_URI=sqlite:///sqlite.db
      - OPENAI_API_KEY=sk-
      - REDIS_URI=redis://redis:6379
      - PINECONE_API_KEY=cf2
      - PINECONE_ENV_NAME=us-east-1
      - PINECONE_INDEX_NAME=pdf-rag
      - UPLOAD_URL=http://local-do-files:8050
      - LANGFUSE_PUBLIC_KEY=SECRET_KEY
      - LANGFUSE_SECRET_KEY=cf
    command: inv dev
    depends_on:
      - redis
      - local-do-files

  worker:
    build: .
    command: celery -A app.celery.celery worker --loglevel=info
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_APP=app.web
      - FLASK_ENV=development
      - SECRET_KEY=123
      - SQLALCHEMY_DATABASE_URI=sqlite:///sqlite.db
      - OPENAI_API_KEY=sk-
      - REDIS_URI=redis://redis:6379
      - PINECONE_API_KEY=cf2
      - PINECONE_ENV_NAME=us-east-1
      - PINECONE_INDEX_NAME=pdf-rag
      - UPLOAD_URL=http://local-do-files:8050
      - LANGFUSE_PUBLIC_KEY=SECRET_KEY
      - LANGFUSE_SECRET_KEY=cf
    depends_on:
      - app
      - redis


  local-do-files:
    build:
      context: .
      dockerfile: Dockerfile-upload
    ports:
      - "8050:8050"
    command: python app.py

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # init-db:
  #   build: .
  #   command: flask --app app.web init-db
  #   environment:
  #     - FLASK_APP=app.web
  #   depends_on:
  #     - redis
