version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:8000"
    volumes:
      - .:/usr/src/app
      - /opt/instance:/usr/src/app/instance
    environment:
      - FLASK_APP
      - FLASK_ENV
      - SECRET_KEY
      - SQLALCHEMY_DATABASE_URI
      - OPENAI_API_KEY
      - REDIS_URI
      - PINECONE_API_KEY
      - PINECONE_ENV_NAME
      - PINECONE_INDEX_NAME
      - UPLOAD_URL
      - LANGFUSE_PUBLIC_KEY
      - LANGFUSE_SECRET_KEY
      - OPENAI_API_BASE_URL
      - OPENAI_API_KEY
    command: /bin/bash -c "inv dev"
    depends_on:
      - redis
      - local-do-files

  worker:
    build: .
    command: inv devworker
    volumes:
      - .:/usr/src/app
      - /opt/instance:/usr/src/app/instance
    environment:
      - FLASK_APP
      - FLASK_ENV
      - SECRET_KEY
      - SQLALCHEMY_DATABASE_URI
      - OPENAI_API_KEY
      - REDIS_URI
      - PINECONE_API_KEY
      - PINECONE_ENV_NAME
      - PINECONE_INDEX_NAME
      - UPLOAD_URL
      - LANGFUSE_PUBLIC_KEY
      - LANGFUSE_SECRET_KEY
      - OPENAI_EMBEDDING_BASE_URL
      - OPENAI_EMBEDDING_KEY
    depends_on:
      - app
      - redis

  local-do-files:
    build:
      context: .
      dockerfile: Dockerfile-upload
    ports:
      - "8050:8050"
    command: python app.py

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  init-db:
    build: .
    command: flask --app app.web init-db
    profiles:
      - db-init
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
      - /opt/instance:/usr/src/app/instance
    environment:
      - FLASK_APP
      - FLASK_ENV
      - SECRET_KEY
      - SQLALCHEMY_DATABASE_URI
      - OPENAI_API_KEY
      - REDIS_URI
      - PINECONE_API_KEY
      - PINECONE_ENV_NAME
      - PINECONE_INDEX_NAME
      - UPLOAD_URL
      - LANGFUSE_PUBLIC_KEY
      - LANGFUSE_SECRET_KEY
      - OPENAI_API_BASE_URL
