version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:8000"
    volumes:
      - .:/usr/src/app
      - /opt/instance:/usr/src/app/instance
    command: /bin/bash -c "inv dev"
    depends_on:
      - redis
      - local-do-files

  worker:
    build: .
    command: inv devworker
    volumes:
      - .:/usr/src/app
      - /opt/instance:/usr/src/app/instance
    depends_on:
      - app
      - redis

  local-do-files:
    build:
      context: .
      dockerfile: Dockerfile-upload
    ports:
      - "8050:8050"
    command: python app.py

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  init-db:
    build: .
    command: flask --app app.web init-db
    profiles:
      - db-init
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
      - /opt/instance:/usr/src/app/instance
